version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    ports:
      - 3308:3306
    volumes:
      - ./data:/var/lib/mysql