name: Application build

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  MYSQL_DB_ROOT_PASSWORD: ${{ secrets.MYSQL_DB_ROOT_PASSWORD }}
  MYSQL_DB_NAME: ${{ secrets.MYSQL_DB_NAME }}
  MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
  VITE_SECRET_KEY_JWT: ${{ secrets.VITE_SECRET_KEY_JWT }}
  VITE_API_URL: ${{ secrets.VITE_API_URL }}
  MYSQL_DB_USER: ${{ secrets.MYSQL_DB_USER }}
  MYSQL_DB_HOST: ${{ secrets.MYSQL_DB_HOST }}
  MYSQL_DB_PORT: ${{ secrets.MYSQL_DB_PORT }}
  SECRET_KEY_JWT: ${{ secrets.SECRET_KEY_JWT }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENAI_PROJECT: ${{ secrets.OPENAI_PROJECT }}
  OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
  OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}

jobs:
  build-and-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Backend .env file
        run: |
          cd Backend
          touch .env
          echo "MYSQL_DB_ROOT_PASSWORD=$MYSQL_DB_ROOT_PASSWORD" >> .env
          echo "MYSQL_DB_NAME=$MYSQL_DB_NAME" >> .env
          echo "MYSQL_DB_PASSWORD=$MYSQL_DB_PASSWORD" >> .env
          echo "MYSQL_DB_USER=$MYSQL_DB_USER" >> .env
          echo "MYSQL_DB_HOST=$MYSQL_DB_HOST" >> .env
          echo "MYSQL_DB_PORT=$MYSQL_DB_PORT" >> .env
          echo "SECRET_KEY_JWT=$SECRET_KEY_JWT" >> .env
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
          echo "OPENAI_PROJECT=$OPENAI_PROJECT" >> .env
          echo "OPENAI_ORGANIZATION=$OPENAI_ORGANIZATION" >> .env
          echo "OPENAI_MODEL=$OPENAI_MODEL" >> .env

      - name: Create Frontend .env file
        run: |
          cd Frontend
          touch .env
          echo "VITE_SECRET_KEY_JWT=$VITE_SECRET_KEY_JWT" >> .env
          echo "VITE_API_URL=$VITE_API_URL" >> .env

      - name: Create DB .env file
        run: |
          touch .env
          echo "MYSQL_DB_ROOT_PASSWORD=$MYSQL_DB_ROOT_PASSWORD" >> .env
          echo "MYSQL_DB_NAME=$MYSQL_DB_NAME" >> .env
          echo "MYSQL_DB_PASSWORD=$MYSQL_DB_PASSWORD" >> .env
          echo "MYSQL_DB_USER=$MYSQL_DB_USER" >> .env
          echo "MYSQL_DB_HOST=$MYSQL_DB_HOST" >> .env
          echo "MYSQL_DB_PORT=$MYSQL_DB_PORT" >> .env

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        run: .github/docker_build_and_push.sh
