name: Cloud Build Trigger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCLOUname: Cloud Build Trigger

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json

      - name: Submit build to Cloud Build
        run: gcloud builds submit --config=cloudbuild.yml .D_KEY }}" > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json

      - name: Submit build to Cloud Build
        run: gcloud builds submit --config=cloudbuild.yaml .