name: Docker Compose Build and Push

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      MYSQL_DB_ROOT_PASSWORD: ${{ secrets.MYSQL_DB_ROOT_PASSWORD }}
      MYSQL_DB_NAME: ${{ secrets.MYSQL_DB_NAME }}
      MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
      VITE_SECRET_KEY_JWT: ${{ secrets.VITE_SECRET_KEY_JWT }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      MYSQL_DB_USER: ${{ secrets.MYSQL_DB_USER }}
      MYSQL_DB_HOST: ${{ secrets.MYSQL_DB_HOST }}
      MYSQL_DB_PORT: ${{ secrets.MYSQL_DB_PORT }}
      SECRET_KEY_JWT: ${{ secrets.SECRET_KEY_JWT }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_PROJECT: ${{ secrets.OPENAI_PROJECT }}
      OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        run: .github/docker_build_and_push.sh
