name: Terraform
on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Cloud Init
        run: terraform init -backend-config="token=${{ secrets.TF_API_TOKEN }}"

      - name: Terraform Cloud Plan
        run: terraform plan

      - name: Terraform Cloud Apply
        run: terraform apply -auto-approve
