name: Terraform
on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Set Google Cloud credentials
        run: echo "$GOOGLE_CREDENTIALS" > /path/to/google_credentials.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Cloud Apply
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform cloud apply -auto-approve tfplan
